config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :books do
    resources :comments
    resources :requests
  end

  get 'profile', to: 'users#show'

  root to: "books#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, length: { minimum: 2 }, uniqueness: true

  has_many :comments, dependent: :destroy
  has_many :requests, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "placeholder.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :book
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  has_many :books
  has_many :requests
  has_many :comments
  has_many :commented_books, through: :comments, source: :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(books_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to('/books')
    else
      redirect_to('/books/new')
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if authenticate_book_owner(@book)
      @book.update(books_params)
      redirect_to root_path
    else
      flash[:alert] = "You can't edit a book that you don't own"
      redirect_to root_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if authenticate_book_owner(@book)
      @book.destroy
      flash[:notice] = "#{@book.title} deleted successfully"
      redirect_to books_path
    else
      flash[:alert] = "You can't delete a book that you don't own"
      redirect_to books_path
    end
  end

  private

  def books_params
    params.require(:book).permit(:title, :author, :image, :user_id)
  end

  def authenticate_book_owner(book_object)
     current_user.id == book_object.user_id
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @comment = Comment.new
  end

  def create
    @book = Book.find(params[:book_id])

    @comment = @book.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save

    redirect_to('/books')

  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])

    @comment.destroy
    redirect_to '/books'

    flash[:success] = "Comment deleted"
  end

  private

  def comment_params
    params.require(:comment).permit(:comments)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @books = current_user.books
  end

  def new
    @book = Book.find(params[:book_id])
    @request = Request.new
  end

  def create
    @book = Book.find(params[:book_id])

    @request = @book.requests.new(request_params)
    @request.user_id = current_user.id
    @request.book_id = @book.id
    @request.save

    redirect_to('/books')
    flash[:alert] = "You have made a request for #{@book.title}"
  end

  private

  def request_params
    params.require(:request).permit(:requests)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_in_li(body, url, html_options = {})
    active = "active" if current_page?(url)
    content_tag :li, class: active do
      link_to body, url, html_options
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= form_for @book, html: {multipart: true} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.file_field :image %>
  <%= f.submit "Update your book" %>
<% end %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <% if current_user %>
      <% if @books.any? %>
        <% @books.each do |book| %>
          <% if book.user != current_user %>
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <% if book.image.url(:medium) %><br>
                  <%= image_tag book.image.url(:medium) %>
                <% else %><br>
                  <%= image_tag("placeholder.jpg") %>
                <% end %><br>
                <%= button_to "Request to Borrow", new_book_request_path(book), class:"btn btn-success btn-md col-md-12", :method => :get %><br>
                <div class="caption">
                  <h3><%= link_to book.title, book_path(book) %></h3>
                  <h4>by <%= book.author %></h4>
                  <% book.comments[0..2].each do |comment| %>
                    <p> <%= comment.comments %>
                    <% if comment.user == current_user %>
                      <%= link_to book_comment_path(book, comment), method: :delete, data: {confirm: "Are you sure?"} do %>
                      <span class="glyphicon glyphicon-remove delete-comment"></span>
                      <% end %> </p>
                    <% end %>
                    <% if book.comments[3] %>
                      <%= link_to "...", book_path(book) %>
                    <% end %>
                  <% end %>
                  <%= link_to "Comment", new_book_comment_path(book) %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        No books have been added.
      <% end %>
    <% else %>
      You have to be logged in to see your friend's books.
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<%= form_for @book, html: {multipart: true} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.file_field :image %>
  <%= f.submit "Submit your book" %>
<% end %>

app/views/books/show.html.erb
<p><%= @book.title %></p>
<p><%= @book.author %></p>

app/views/comments/new.html.erb
<%= form_for [@book, @comment] do |f| %>
  <%= f.label :comments %>
  <%= f.text_area :comments %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BorrowABook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track': 'reload' %>

    <style>

    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
    .container {
      background-color: #f2f2f2;
      padding: 25px;
      margin-bottom: 100px;
    }

    .row {
      margin: 25px;
    }

    .box {
    padding: 0 5px 0 5px;
    }

    .inner {
    background-color: lavender;
    }

  </style>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Borrow My Book</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <li> <%= link_to_in_li 'Home', books_path %></li>
            <li> <%= link_to_in_li 'Add a book', new_book_path %></li>
            <li> <%= link_to_in_li 'My books', profile_path %></li>
            <li> <%= link_to_in_li 'Incoming Requests', book_requests_path(current_user.id) %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to_in_li "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to_in_li "Login", new_user_session_path %></li>
              <li><%= link_to_in_li"Login with Facebook", user_facebook_omniauth_authorize_path %></li>
              <li><%= link_to_in_li "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/requests/index.html.erb
<div class="container">
  <div class="row">
    <% if @books.any? %>
      <% @books.each do |book| %>
      <% if book.requests.any? %>
        <% book.requests.each do |request| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
              <%= image_tag request.book.image.url(:medium) %>
              <div class="caption">
                <h3><%= request.book.title %></h3>
                <p> <%= request.user.email %> would like to borrow this book. </p>
              </div>
          </div>
        </div>
        <% end %>
      <% end %>
      <% end %>
    <% else %>
      <p> No one has requested to borrow any of your books yet. </p>
    <% end %>
  </div>
</div>

app/views/requests/new.html.erb
<%= form_for [@book, @request] do |f| %>
  <%= f.label :request_from %>
  <%= f.date_field :request_from %>
  <%= f.label :request_to %>
  <%= f.date_field :request_to %>
  <%= f.submit "Request #{@book.title}" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <% if @user.books.any? %>
      <% @user.books.each do |book| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <% if book.image.url(:medium) %>
            <br>
            <%= image_tag book.image.url(:medium) %><br>
            <% else %>
            <br>
            <%= image_tag("placeholder.jpg") %><br>
            <% end %>
              <%= button_to "Edit", edit_book_path(book), class:"btn btn-info btn-md col-md-6", :method => :get %>
              <%= button_to "Delete", book_path(book), class:"btn btn-danger btn-md col-md-6", method: :delete, data: { confirm: "Are you sure?" } %><br>
            <div class="caption">
              <h3><%= link_to book.title, book_path(book) %></h3>
              <h4>by <%= book.author %></h4>
            </div>
          </div>
        </div>
        <% end %>
    <% else %>
      <p> You haven't added any books yet. </p>
    <% end %>
  </div>
</div>